services:
  sanity-studio:
    build: 
      context: ./packages/studio
      target: development
      args: # TODO: Use just .env.local for project ID
        - PROJECT_ID=${SANITY_PROJECT_ID}
    ports:
      - 3333:3333
    environment:
      - PORT=3333